#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1476267616                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : #https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Best IP tv player !.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Radhouani Malek                                
your_link                                 : #https://emilbaehr.com                     
your_city                                 : Paris                                
email_address                             : redmakapps@gmail.com
facebook_username                         :                                           
instagram_username                        : #ebaehr
twitter_username                          : #ebaehr
github_username                           : red-mak
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : One purchase, tree applications.
    description                           : Purchase once and get an iPhone, iPad and AppleTV application!
    fontawesome_icon_name                 : dollar-sign

  - title                                 : Your Favorite/Watched media are synced over all your devices.
    description                           : Start a movie or a serie on your iPhone and continue watching on your AppleTV.
    fontawesome_icon_name                 : sync-alt

  - title                                 : Fast parsing
    description                           : iProTv uses best algorithme to parse your m3u files!
    fontawesome_icon_name                 : fighter-jet

  - title                                 : Almost all video formats are handled.
    description                           : iProTv uses VLC player to play all video formats.
    fontawesome_icon_name                 : video

  - title                                 : Resume where you stop.
    description                           : Resume where you stop watching (even this is synced :) )
    fontawesome_icon_name                 : play
  
  - title                                 : 6 frofiles !
    description                           : Every member of your family have a unique prifile, everyone is happy.
    fontawesome_icon_name                 : id-card

  - title                                 : Dark/light mode
    description                           : iProTv follow the iOS/tvOS settings, it will update the interface everytime you change to dark or light mode.
    fontawesome_icon_name                 : adjust

  - title                                 : Gorgeous interface.
    description                           : iProTv is designed for the ease of use and follow Apple UX guide lines.
    fontawesome_icon_name                 : palette

  - title                                 : 4K support
    description                           : iProTv support 4k video!
    fontawesome_icon_name                 : border-none

  - title                                 : High efficiency
    description                           : iProTv is developed to use less ressources so it will not drain you battery like other apps ;)
    fontawesome_icon_name                 : battery-three-quarters



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown